# Generated by Django 5.0.6 on 2024-05-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetInvoiceAPI', '0006_alter_client_address_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
