# Generated by Django 5.0.6 on 2024-05-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetInvoiceAPI', '0007_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
