# Generated by Django 5.0.6 on 2024-05-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetInvoiceAPI', '0011_alter_invoice_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='vat',
            field=models.IntegerField(default=21),
        ),
    ]
