# Generated by Django 5.0.6 on 2024-05-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetInvoiceAPI', '0012_invoice_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
