# Generated by Django 5.0.6 on 2024-05-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetInvoiceAPI', '0013_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='vat',
            field=models.IntegerField(default=21),
        ),
    ]
