# Generated by Django 5.0.6 on 2024-05-24 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetInvoiceAPI', '0014_budget_approved_budget_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='BudgetInvoiceAPI.budget'),
        ),
    ]
