# Generated by Django 5.0.6 on 2024-05-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetInvoiceAPI', '0016_budget_date_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='doc_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='doc_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
